### ISSUE TITLE
Some pages crash because the client cannot reach `Cloud Firestore backend`

### ISSUE THREAD

**Issue by timothyparez** [AvaloniaUI/Documentation#143]
If the client does not have access to Google/Firebase certain pages simply crash.

For example: https://docs.avaloniaui.net/docs/getting-started/ide-support/jetbrains-rider-setup

![image](https://user-images.githubusercontent.com/2060470/139184080-4da3d8e1-6be9-4dfa-8955-36fb4b0a9642.png)

**Comment by MikeCodesDotNET** [comment]
Is this still a problem for you?

**Comment by penenkel** [comment]
I can confirm that this issue still exists. I'm in a corporate network and all traffic is/should be routed through a proxy.

![image](https://user-images.githubusercontent.com/7736404/166816389-88e17e2e-0f35-4be0-83a2-d4b44e454db5.png)
