### ISSUE TITLE
dead images on Templates page, other places

### ISSUE THREAD

**Issue by binary1230** [AvaloniaUI/Documentation#16]
Hi, let me know if this info is useful or this is the right channel for it.

On this page:
https://docs.avaloniaui.net/docs/templates/data-templates

There are several broken images. Example of one broken link:
http://avaloniaui.net/docs/templates/images/hello-world-button.png

Here was the original image (retrieved from archive.org)
![hello-world-button](https://user-images.githubusercontent.com/5413064/119238939-b0357c00-bb13-11eb-96e0-abe4ef114e11.png)
https://web.archive.org/web/20200426183704if_/https://avaloniaui.net/docs/templates/images/hello-world-button.png

--------

I was attempting to submit a PR with a fix but couldn't figure out the current asset path, I'm guessing this is related to some info I had seen about migrating to the new website so understand it's WIP.

I'm currently learning AvaloniaUI so I'm bouncing in and out of the docs frequently.  If reporting further issues here is useful for you guys, I can keep doing so. If you have any info on how to fix stuff like this, happy to submit PRs as I encounter them.

Thanks!

**Comment by MikeCodesDotNET** [comment]
Looks like this is resolved on the latest docs.
