### ISSUE TITLE
[Feature Request] Offline download and run locally

### ISSUE THREAD

**Issue by SpaceNerden** [AvaloniaUI/Documentation#177]
By run download and run locally I mean like [the main avaloniaui.net](https://github.com/AvaloniaUI/avaloniaui.net) repository

I think it will help those who are planning to try Avalonia while they are travelling or while they have no internet access (Like me soon)

**Comment by MikeCodesDotNET** [comment]
Hey, 

I'm not sure I understand what it is you're trying to do. You can clone the repo and run it locally and you'll find out docs content here as markdown.

**Comment by SpaceNerden** [comment]
Yup, thats what I ended up doing. Thanks for replying!
