### ISSUE TITLE
Documentation for DataGrid.

### ISSUE THREAD

**Issue by entvex** [AvaloniaUI/Documentation#2]
Dear AvaloniaUI community.
I am working on a open source application. Where i plan on using the DataGrid, but it seem that any mention or sample is missing for the documentation. Would a pull request be accepted if i made one with a small example ?

**Comment by danwalmsley** [comment]
A PR would be very welcome!

**Comment by entvex** [comment]
Dear @danwalmsley I have created pull request #4 please review it, and accept it, if there is no comments to it 👍. 
I would like to ask if you have any experience in using the DataGrid with MVVM? Because I am not really sure how access the data using a contextmenu while using commands :)? I hope it my question makes sense :)
