### ISSUE TITLE
Simple "Hello-World" Tutorial

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/Documentation#202]
We need a very basic Tutorial for people to get started, if they don't have WPF or other XAML background. 

This should cover:
- What is XAML, what is MVVM, why do I need this?
- Using panels for layout
- Using Bindings
- Using MVVM 
- Using Events
- Basic User-Input

Any ideas are welcome.

**Comment by MikeCodesDotNET** [comment]
Hey @timunie, 

What are your thoughts on the benefits of us maintaining this instead of linking to existing content from other providers? I know Microsoft has some good docs that cover the basics such as 'what is xaml' and 'what is MVVM'. 

Cheers,
Mike J

**Comment by timunie** [comment]
I don't care. If the links are reliable and the core team agrees, why not?

@danwalmsley what are your thoughts on this?

**Comment by MikeCodesDotNET** [comment]
We already have [some docs](https://docs.avaloniaui.net/docs/getting-started/programming-with-avalonia/the-model-view-viewmodel-pattern-mvvm) like what you requested, so it'd be useful to understand what we're missing :)

**Comment by timunie** [comment]
Well this issue came from a discussion on telegram were someone, I think it was dan but not sure, thought it would be a good idea to have this. The todo tutorial is too much for someone completely new to XAML and MVVM. I myself don't need such a tutorial anymore, but wanted to add it if I find some free time to do. And to not forget, I opened the issue back then.
