### ISSUE TITLE
Panel which put child elements in single line and stretches them equally

### ISSUE THREAD

**Issue by iwtu** [AvaloniaUI/Documentation#23]
Hi.
Is a better and simpler way how to achieve it, e.g. by StackPanel?

The following Grid works but there it much boilerplate code.

```xaml
<Grid ColumnDefinitions="*,*,*,*" Classes="stretchChildren">
          <ContentControl Content="{Binding SelectBox1}" Grid.Column="0"/>
          <ContentControl Content="{Binding SelectBox2}" Grid.Column="1"/>
          <ContentControl Content="{Binding SelectBox3}" Grid.Column="2"/>
          <ContentControl Content="{Binding SelectBox4}" Grid.Column="3"/>
 </Grid>
```

**Comment by maxkatz6** [comment]
```
<UniformGrid Columns="4">
          <ContentControl Content="{Binding SelectBox1}" />
          <ContentControl Content="{Binding SelectBox2}" />
          <ContentControl Content="{Binding SelectBox3}" />
          <ContentControl Content="{Binding SelectBox4}" />
</UniformGrid>
```

**Comment by iwtu** [comment]
@maxkatz6 Thanks, it works. I couldn't find in the [documentation](https://docs.avaloniaui.net/docs/layout)

Can I ask why it works only with Grid or UniformGrid and not with StackPanel or DockPanel?
Thanks

**Comment by maxkatz6** [comment]
@iwtu different controls have different responsibilities. Although Grid can pretty much replace UniformGrid with some additional bolierplate. 
StackPanel, for instance, does not fills whole available space. I.e. when Grid measures controls to fit its available size, StackPanel allows children to have as much space as they want. With that behavior StackPanel resulting size can be smaller than available size or bigger than it (in that case it will be cropped, unless you will use ScrollViewer).
