### ISSUE TITLE
Documentation is hard on the eyes

### ISSUE THREAD

**Issue by Xerxes004** [AvaloniaUI/Documentation#238]
**Describe the bug**
The Avalonia documentation has really bad contrast for monospaced text in Brave browser. It's very hard to read.

**To Reproduce**

1. Use arm64 Brave browser on MacOS Catalina 12.3
1. Go to https://docs.avaloniaui.net/docs/data-binding/the-datacontext
1. Use eyeballs

**Expected behavior**
Documentation that doesn't hurt my eyes

**Screenshots**
https://imgur.com/a/z7wAsfU

**Desktop (please complete the following information):**

- OS: MacOS 12.3
- Brave Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (arm64)
- Chrome Version 100.0.4896.127 (Official Build) (arm64)

**Comment by FoggyFinder** [comment]
> Shouldn't this be an issue for the Brave browser then? I'm not sure it's worth the time for Avalonia to try to support every non-mainstream browser.

Brave is popular enough to support it.

**Comment by grokys** [comment]
I'm not seeing this on Chrome:

![image](https://user-images.githubusercontent.com/1775141/163586045-7aade104-111a-456f-bd32-c24ba3b8290c.png)

**Comment by Xerxes004** [comment]
@grokys It's possible this only applies to arm64 and/or MacOS. If anyone can point me to how to change the styles in the repo I will fix it and make a PR.

**Comment by FoggyFinder** [comment]
> 1. Use Brave browser

@Xerxes004 not enough to replicate. I have Brave and the site looks fine there.

**Comment by maxkatz6** [comment]
Avalonia uses GitBook and styles provided from them.
I don't know for sure if we can modify these styles, but you should be able to find wrong ones using browser dev tools.

**Comment by MikeCodesDotNET** [comment]
@FoggyFinder Are you using an M1 Mac? 

@Xerxes004, as mentioned, we use GitBook and don't have a huge amount of control over the CSS. This might be an issue that we need to log with GitBook themselves.

**Comment by FoggyFinder** [comment]
> Are you using an M1 Mac?

@MikeCodesDotNET no, Windows. Steps to reproduce were edited (clarified) after my comment.

**Comment by Xerxes004** [comment]
This is fixed for me now.
