### ISSUE TITLE
Add DataValidationErrors documentation

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Documentation#278]
It seems currently we don't have much of validation documentation.
So following should be added.
1. Default validation approaches:
- Data Annotation attributes (example [DataAnnotationsErrorViewModel.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/BindingDemo/ViewModels/DataAnnotationsErrorViewModel.cs))
- Exception in the setter (example [ExceptionErrorViewModel.cs](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/BindingDemo/ViewModels/ExceptionErrorViewModel.cs))
- INotifyDataErrorInfo implementation (example [IndeiErrorViewModel](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/BindingDemo/ViewModels/IndeiErrorViewModel.cs))
- Optionally a link to ReactiveUI documentation - https://www.reactiveui.net/docs/handbook/user-input-validation/ which works with Avalonia just as well (INotifyDataErrorInfo used internally)
2. Some examples how to style default error template (example https://github.com/AvaloniaUI/Avalonia/discussions/8282#discussioncomment-2886973 )
3. And how to implement support for DataValidationErrors control inside of developer's custom control (see discussion [here](https://github.com/AvaloniaUI/Avalonia/discussions/8282#discussioncomment-2886973))

**Comment by timunie** [comment]
@maxkatz6 can you assign me?
