### ISSUE TITLE
Missing InitializeComponent()?

### ISSUE THREAD

**Issue by ApiumJacob** [AvaloniaUI/Documentation#298]
I'm following this tutorial and I think this section is missing some code (but I'm not sure).

https://docs.avaloniaui.net/tutorials/todo-list-app/creating-a-view#the-usercontrol

I think the code should read:
```
using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace Todo.Views
{
    public partial class TodoListView : UserControl
    {
        public TodoListView()
        {
            InitializeComponent();
        }
        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

**Comment by maxkatz6** [comment]
With [XamlNameReferenceGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) nuget package InitializeComponent is autogenerated automatically. Similarly as it is in WPF or UWP if you are familiar.
