### ISSUE TITLE
Images are absent for the Music Store sample

### ISSUE THREAD

**Issue by Mihier-Roy** [AvaloniaUI/Documentation#335]
The images for the Music Store app do not load. A cursory look at the locations the links point to returns a 'Not Found'. Possible that they are no longer hosted?

**Comment by timunie** [comment]
@Mihier-Roy I'm planning to move this sample to another location and also providing the entire code there. But it will take some time to do.

**Comment by Mihier-Roy** [comment]
@timunie no worries, take your time 😄

**Comment by JimmyCushnie** [comment]
In the meantime, the images can be found on the Internet Archive. https://web.archive.org/web/20210612223406/https://docs.avaloniaui.net/tutorials/music-store-app
