### ISSUE TITLE
How to add event to control inside TemplatedControl

### ISSUE THREAD

**Issue by tivewsalaeharad** [AvaloniaUI/Documentation#382]
I have a TemplatedControl and some daughter controls inside it. I want to assign them some events. Initially axaml file cannot access C# module, but when I add `x:Class="MyNamespace.MyTemplatedControl"` to axaml, although C# code is seen from it, an error occurs:

>   MyTemplatedControl.axaml(9, 6): [XAMLIL] No Content property or any Add methods found for type MyDesktopApp:MyNamespace.MyTemplatedControl Line 9, position 6.

Looking for solution, all I have found was  [this variant with Button and its Command property](https://stackoverflow.com/questions/73978779/assign-button-click-event-through-templatebinding-on-avalonia). But in this case I will be restricted only with click event, without opportunity to handle text changed, drag and drop, getting and loosing input focus and other popular actions.

MyTemplatedControl.axaml:
```
<Styles xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:controls="using:MyNamespace"
        x:Class="MyNamespace.MyTemplatedControl">
    <Design.PreviewWith>
        <controls:MyTemplatedControl />
    </Design.PreviewWith>

    <Style Selector="controls|MyTemplatedControl">
        <!-- Set Defaults -->
        <Setter Property="Template">
            <ControlTemplate>
                <StackPanel>
                    <TextBlock
                        Text="Templated Control"
                        DoubleTapped="InputElement_OnTapped"/>
                    <TextBox
                        KeyDown="InputElement_OnKeyDown"/>
                </StackPanel>
            </ControlTemplate>
        </Setter>
    </Style>
</Styles>
```

MyTmplatedControl.axaml.cs:
```
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;

namespace MyNamespace;

public class MyTemplatedControl : TemplatedControl
{
    private void InputElement_OnTapped(object? sender, RoutedEventArgs e)
    {
        (sender as TextBlock).Text = "DOUBLE TAPPED";
    }

    private void InputElement_OnKeyDown(object? sender, KeyEventArgs e)
    {
        (sender as TextBox).Background = new SolidColorBrush(Colors.Green);
    }
}
```

PS. As a beginner, I also don't know yet, how to access controls from .axaml.cs to .axaml, help me, if it is possible, but I think, this is a topic for another issue.

**Comment by maxkatz6** [comment]
> PS. As a beginner, I also don't know yet, how to access controls from .axaml.cs to .axaml, help me, if it is possible, but I think, this is a topic for another issue.

For beginners I would recommend UserControls, which have XAML and C# files combined into a single .NET class/type. Event handlers are also visible there from XAML.
TemplatedControl is usually used by the control creators, who want their controls to be used by other developers and be easily restylable. As with templated controls XAML is detached from the control class, which means you can easily replace it.

> when I add x:Class="MyNamespace.MyTemplatedControl" to axaml, although C# code is seen from it, an error occurs:

As I mentioned above, templated control XAML files are detached from the C# class, so you can't use them as a x:Class.
`x:Class` requires both XAML and class to be of the same type, for example both can be a UserControl type, or both can be a Window type. But with templated control it happens to be Style type in XAML and TemplatedControl type in C# code, so it can't be used together.
Technically you could create a separated C# class inherited from Style and use it in x:Class. And define events there, but it can be dangerous, as these methods will be shared between all control instances using this style, and memory leaks might be possible.

**Comment by tivewsalaeharad** [comment]
@maxkatz6 thank you for help. But here is one feature: I want to make control, that has different content, depending on its properties [like here](https://github.com/AvaloniaUI/Avalonia/issues/1434#issuecomment-1352592231).
It is possible with TemplatedControl, but can it be realized with UserControl?
