### ISSUE TITLE
Blocked or erroring JavaScript breaks some basic website functionality

### ISSUE THREAD

**Issue by chylex** [AvaloniaUI/Documentation#384]
Hi, I ran into an issue where one of the JavaScript files the documentation page loads got accidentally blocked by an addon, which broke a few basic features of the website that in my opinion should not need JavaScript to function.

You can simulate it by going to https://docs.avaloniaui.net/docs/getting-started/ide-support and blocking JavaScript in your browser's Dev Tools. Observe that:

- Images don't load
- In the right sidebar, clicking "Edit on GitHub" or any of the anchors under "On This Page" does nothing
  - Since all of these are fake "links", they break basic browser functionality like the ability to see where the links go, or middle-clicking or Ctrl-clicking them to open it in a new tab
- The search field on top right cannot be focused and typed into

There are obviously more things that break without JavaScript, but I consider the things I listed to be basic website functionality that does not need JavaScript to function, and should instead be [progressively enhanced](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement) when JavaScript is loaded.

It's likely an issue with GitBook, but that appears to be some commercial solution that does not have an open issue tracker. I would appreciate it if you could bring these issues up with them.

**Comment by maxkatz6** [comment]
New web site doesn't require JS to be enabled https://docs.avaloniaui.net/
