### ISSUE TITLE
How to add styles to Expander control

### ISSUE THREAD

**Issue by tivewsalaeharad** [AvaloniaUI/Documentation#385]
Can someone help me with manual or list of styleable attributes for Expander control. Here I want to remove marked spaces to make my control instance with text as compact as possible. Changing ToggleButton style inside Expander had no result. I tried to change properties of compounds in Debugger Window (Visual Tree), but they also didn't bring any desirable result.

![изображение](https://user-images.githubusercontent.com/25724579/209054716-2dff6254-ad66-4334-b1e3-a1c3d2447c3d.png)

My axaml:

````
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:windows="clr-namespace:MyApp.Windows"
        mc:Ignorable="d" d:DesignWidth="500" d:DesignHeight="300"
        x:Class="MyApp.Windows.Window1"
        Title="Window1">
    <StackPanel>
        <Expander Header="My Expander">
            <Expander.Styles>
                <Style Selector="ToggleButton">
                    <Setter Property="Padding" Value="0"/>
                </Style>
            </Expander.Styles>
            <ListBox
                Items="{Binding RelativeSource={RelativeSource AncestorType={x:Type windows:Window1}}, Path=Variants}"/>
        </Expander>
    </StackPanel>
</Window>
````

**Comment by rabbitism** [comment]
Sorry for late reply. Here are some values you can change that potentially can reduce spacing:
1. Update `MinHeight` to reduce header Height
2. overwrite Resource `ExpanderChevronButtonSize` to reduce arrow button height
3. Update Padding to reduce content padding. 
![image](https://user-images.githubusercontent.com/14807942/212479890-49701888-7f75-40a4-9467-45ea53cd493c.png)

**Comment by tivewsalaeharad** [comment]
@rabbitism hello. I tried. It works partially
Finally I decided to make my own expander view

**Comment by rabbitism** [comment]
> Hello @rabbitism! I tried. It works partially
> Finally I decided to make my own expander view

This is quite a while ago. :) maybe things has changed.
