### ISSUE TITLE
[Feature] Add Support at Documentation version

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/Documentation#393]
Add support to Document version linked to Avalonia Version like readthedocs do.

> **Note**
>Eg.: https://docs.nextcloud.com/server/latest/admin_manual/index.html at the bottom of the side menu it is possible to select the nextcloud version to which the documentation refers.

**Comment by maxkatz6** [comment]
We were thinking about copying current documentation to another repository and domain. Or possibly making a separated 0.10 branch and still move it to another domain.
While move this repo main branch and domain to the 11.0 exclusively.

Alternatively, we could duplicate documentation into different folders, as it seems to be dome sometimes, but I would want to avoid that.

I don't see anything useful in gitbook that would help as to do it better. Some third-party plugins like https://github.com/prescottprue/gitbook-plugin-versions-select can be used to add a selector between domains and that's it.

Anyway, anybody with experience with these documentation engines is needed.

**Comment by maxkatz6** [comment]
https://github.com/AvaloniaUI/avalonia-docs has multiple version support now!
