### ISSUE TITLE
Avalonia 11.0 documentation requests

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/Documentation#399]
Must be added before 11.0 release:
- [ ] ControlTheme documentation, comparison with 0.10 styling. Also would require updating Troubleshooting page. @grokys 
- [ ] ThemeDictionaries + ThemeVariants (can be mostly copy pasted from the https://github.com/AvaloniaUI/Avalonia/pull/8166) @maxkatz6 
- [ ] OnPlatform markup extension @maxkatz6 
- [ ] TextBlock Inlines @Gillibald 
- [ ] New StorageProvider API @maxkatz6 
- [ ] Update CompiledBindings page, as most of old issues were solved and it's possible to enable them globally now
- [ ] Update supported platforms page. Make sure macOS min supported version fully supports Metal API, as we plan to switch to Metal mid 11.x.
- [ ] New controls documentation pages (ColorPicker, DrowDownButton, RefreshContainer...)
- [ ] Effects API https://github.com/AvaloniaUI/Avalonia/pull/11014 (+ not sure if box shadow was documented before)
- [ ] Document RenderOptions (especially since we have different defaults now) https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Media/RenderOptions.cs#L7
- [ ] https://github.com/AvaloniaUI/Documentation/issues/438

Nice to have
- [ ] GPU low level interop (see https://github.com/AvaloniaUI/Avalonia/pull/10014) @kekekeks 
- [ ] Move breaking changes page from the Avalonia repo wiki to the documentation page. Format it properly.
- [ ] New events interaction gestures like BackRequested, Holding, pinch.
- [ ] Automation APIs
- [ ] Documentation on custom markup extension (including new OptionsMarkupExtensions)
- [ ] Runtime XAML parsing API which was improved in the 11.0
- [ ] Notes about System.Reactive removal?
- [ ] https://github.com/AvaloniaUI/Documentation/issues/303
- [ ] https://github.com/AvaloniaUI/Documentation/issues/423
- [ ] https://github.com/AvaloniaUI/Avalonia/issues/6960

Won't be added:
- Composition related documentation. It's not considered stable atm, and might have heavy changes during the 11.x timeline.

Something from the 0.10 that really should be documented. Note, there are a lot more missing documentation pages, but I want to mention here major Avalonia features that get lots of questions about.:
- [ ] Control lifecycle (was changed in the 11.0 with Loaded/Unloaded events)
- [ ] NativeControlHost
- [ ] Headless API

**Comment by grokys** [comment]
We should clarify that using a style to bind to `ListBoxItem.IsSelected` isn't supported in 11.0:

https://github.com/AvaloniaUI/Avalonia/issues/10249#issuecomment-1429752777

**Comment by workgroupengineering** [comment]
Add documentation for  [OnFormFactor](https://github.com/AvaloniaUI/Avalonia/blob/955a53595f7a4bcc1473f1d9e0a9a078cc146f3a/src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/OnFormFactorExtension.cs#L27)

Add ItemContainerTheme for MenuItem , Treeview, ecc...

**Comment by maxkatz6** [comment]
Closed in favor off https://github.com/AvaloniaUI/avalonia-docs/issues/20
