### ISSUE TITLE
fixing namespace does not resprect prefix defined in XmlnsPrefixAttribute

### ISSUE THREAD

**Issue by tisis2** [AvaloniaUI/Documentation#407]
Hi there,

i started creating a lib with a markup extension at the moment and i faced the situation that the namespce prefix was not respected like i was expected it to be. i added the attributes to my library but in the xaml editor the namespace was created with another prefix. i am using Rider with the Avalonia Plugin

![gif_47](https://user-images.githubusercontent.com/18416393/225661037-5fe91671-43b1-405e-a0b9-b72fa0f9a5f6.gif)

or am i interpreting the attribute in a wrong way?

the same thing in WPF uses the prefix defined in the AssemblyInfo
![gif_48](https://user-images.githubusercontent.com/18416393/225663332-a0b9aee3-6ee4-49ef-ad31-aa81954366d4.gif)

**Comment by maxkatz6** [comment]
It seems to be an issue in Rider itself. As we don't provide namespace fixing feature.

**Comment by tisis2** [comment]
I thought maybe it is just caused by the fact that avalonia uses a different namespace for the xmlns attributes. but i wonder why the value of XmlnsDefinitionAttribute is used correctly but XmlnsPrefixAttribute is not. for me some how it seems there would be a namespace fixing feature otherwise none of the aspects should work

**Comment by maxkatz6** [comment]
Rider understands XmlnsDefinitionAttribute from avalonia namespace. But it seems not completely.
Can you recreate this issue on their youtrack? https://youtrack.jetbrains.com/issues/rider

**Comment by tisis2** [comment]
https://youtrack.jetbrains.com/issue/RIDER-91081/Avalonia-XAML-the-import-type-fix-does-not-respect-the-XmlnsPrefixAttribute-of-Avalonia

**Comment by maxkatz6** [comment]
@tisis2 thanks! Added this issue to this page https://github.com/AvaloniaUI/Avalonia/issues/10356
