### ISSUE TITLE
SilenceConsole - Console.Read vs Console.ReadKey

### ISSUE THREAD

**Issue by mikegoatly** [AvaloniaUI/Documentation#411]
In the [Running your Avalonia app on a Raspberry Pi with Raspbian Lite](https://docs.avaloniaui.net/guides/deep-dives/running-on-raspbian-lite-via-drm) the `SilenceConsole` method reads as:

``` csharp
private static void SilenceConsole()
{
    new Thread(() =>
        {
            Console.CursorVisible = false;
            while (true)
                Console.ReadKey(true);
        })
        { IsBackground = true }.Start();
}
```

Under normal conditions this works fine, but I've found it causes problems when it's run from `systemd` (I want to do this so my app auto starts on boot and re-start whenever the app exits for whatever reason).

The error I was getting was:

```
Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
```

Changing `Console.ReadKey` to `Console.Read` does make the issue go away and I can't really see a significant difference in behavior, so I would propose making the change in the documentation. If there is a subtle difference I haven't observed, we could always use this:

``` csharp
while (true)
{
    if (Console.IsInputRedirected)
        Console.Read();
    else
        Console.ReadKey();
}
```

Which covers both bases.

**Comment by kekekeks** [comment]
SilenceConsole is a cheap way to disable the blinking terminal cursor. You can skip it if input is redirected.

Technically it could be replaced with `\e[?25l` vt100 sequence

**Comment by mikegoatly** [comment]
Ok, in that case, would adding this to the top of the method make more sense:

``` csharp
if (Console.IsInputRedirected)
{
    return;
}
```
