### ISSUE TITLE
Suggestion: consider other documentation website generators

### ISSUE THREAD

**Issue by alexandrehtrb** [AvaloniaUI/Documentation#416]
Hello,

I really like Avalonia, I think you guys are doing a very good job.

I ocasionally visit the documentation [site](https://docs.avaloniaui.net/) and it feels a like sluggish... have you considered using a different website framework?

Some frameworks seem to be nice, like Vitepress, Docusaurus and Astro.

**Comment by jcyuan** [comment]
where is your location to access the doc site from?
because this sounds more like a network problem.

**Comment by rabbitism** [comment]
I suggested on twitter lol. 
I would prefer `Read The Docs`, take Godot documentation as example. it has great support for multi-language and version. 
https://docs.godotengine.org/en/stable/

**Comment by grokys** [comment]
We're currently working on the new docs portal using Docusaurus here https://github.com/AvaloniaUI/avalonia-docs
