### ISSUE TITLE
No documentation about DataGrid styling

### ISSUE THREAD

**Issue by michalwitek1232** [AvaloniaUI/Documentation#47]
Hi, I saw that there is no entry about DataGrid styling in Avalonia. 
Maybe some update?

**Comment by Arhell** [comment]
https://docs.avaloniaui.net/docs/controls/datagrid

**Comment by michalwitek1232** [comment]
I saw it but there is nothing about real life styling, I guess i need to make another pull request with updates to docs ;3

**Comment by maxkatz6** [comment]
I would say it's the same, ad any other control styling, isn't it? Just find DataGridColumnHeader default/fluent style, for instance, and retemplate it or apply additional styles on top of it. 

Would make more sense to add complex styling examples for any control.
