### ISSUE TITLE
Documentation about transitions is incomplete

### ISSUE THREAD

**Issue by daniel-lerch** [AvaloniaUI/Documentation#50]
The documentation about transitions (`docs/animation/transitions.md`) only lists
- `DoubleTransitions`: For `double` target properties
- `FloatTransitions`: For `float` target properties
- `IntegerTransitions`: For `int` target properties
- `TransformOperationsTransition`: For `ITransform` properties

Avalonia 0.10.6 contains in addition to that
-  `BoxShadowsTransition`
-  `ColorTransition`
- `CornerRadiusTransition`
- `PointTransition`
- `SizeTransition`
- `ThicknessTransition`
- `VectorTransition`

It would be great if these transitions could be added to the documentation.

**Comment by maxkatz6** [comment]
Also https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Visuals/Animation/Transitions/BrushTransition.cs

**Comment by MikeCodesDotNET** [comment]
Adding some tasks to keep track of our progress. 

- [ ] [BrushTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/BrushTransition.cs)
- [ ] [BoxShadowsTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/BoxShadowsTransition.cs)
- [ ] [ColorTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/ColorTransition.cs)
- [ ] [CornerRadiusTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/CornerRadiusTransition.cs)
- [ ] [PointTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/PointTransition.cs)
- [ ] [SizeTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/SizeTransition.cs)
- [ ] [ThicknessTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/ThicknessTransition.cs)
- [ ] [VectorTransition](https://github.com/AvaloniaUI/Avalonia/blob/cba80543048c9f566a17f657d93a5bf22b4006fa/src/Avalonia.Base/Animation/Transitions/VectorTransition.cs)
